
version: "3.5"
services:
    redis:
        image: redis:6.2-alpine
        ports:
            - "6380:6379"
        expose:
            - "6380"
        networks:
            - dockernet
        healthcheck:
            test: redis-cli ping
            interval: 1s
            timeout: 3s
            retries: 30
    api:
        container_name: masivian-challenge
        build:
            context: .
        volumes:
            - ./:/api:rw
        depends_on:
            redis:
                condition: service_healthy
        environment:
            - NODE_ENV=development
            - IN_DOCKER=true
        ports:
            - '3000:3000'
        networks:
            - dockernet

networks:
    dockernet:
        external: false
        name: dockernet

